#!/bin/bash
set -e
echo "=== FaceForge Model Setup ==="
echo ""
echo "1. FLAME 2020 Model"
echo "   Register at: https://flame.is.tue.mpg.de/"
echo "   Download: FLAME2020.zip"
echo "   Extract to: data/pretrained/FLAME2020/"
echo ""
echo "2. MICA Weights"
echo "   Download from: https://zielon.github.io/mica/"
echo "   Place at: data/pretrained/mica.tar"
echo ""
echo "3. InsightFace buffalo_l (auto-download)"
python -c "import insightface; app = insightface.app.FaceAnalysis(name='buffalo_l'); app.prepare(ctx_id=0)" && echo "   InsightFace: OK"
echo ""
echo "4. Verifying device detection..."
python -c "from faceforge.utils.device import get_device; print('   Device:', get_device())"
echo ""
echo "Setup complete. Run: python -m faceforge.cli --help"
